/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.catarina.continua;

import java.awt.Color;

/**
 *
 * @author catarina
 */
public class tela extends javax.swing.JFrame {

    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
        
         // TODO add your handling code here:
        
        //valor de cada pacote 
      Integer pacote01 = 100 * 5000  ;
      Integer pacote02 = 500 * 5000  ;
      Integer pacote03 = 1000 * 5000  ;
       
      //valor da manutenção comum 
      Integer valorReal = 12000;
      
      //diferença de valor
      Integer economia01 =  valorReal - pacote01;
      Integer economia02 =  valorReal - pacote02;
      Integer economia03 =  valorReal - pacote03;
      
      //porcentagem
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntPacote1 = new javax.swing.JButton();
        bntPacote2 = new javax.swing.JButton();
        bntPacote3 = new javax.swing.JButton();
        lbTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbTextoP1 = new javax.swing.JLabel();
        lbTextoP2 = new javax.swing.JLabel();
        lbTextoP3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntPacote1.setBackground(new java.awt.Color(0, 255, 255));
        bntPacote1.setText("calcular");
        bntPacote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPacote1ActionPerformed(evt);
            }
        });

        bntPacote2.setBackground(new java.awt.Color(0, 102, 255));
        bntPacote2.setText("calcular");
        bntPacote2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPacote2ActionPerformed(evt);
            }
        });

        bntPacote3.setBackground(new java.awt.Color(0, 0, 204));
        bntPacote3.setText("calcular");
        bntPacote3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPacote3ActionPerformed(evt);
            }
        });

        lbTexto.setText("total:");
        lbTexto.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel1.setBackground(new java.awt.Color(255, 102, 0));
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Adquira nosso serviço agora mesmo");

        jLabel2.setText("Selecione abaixo o pacote escolhido:");

        lbTextoP1.setBackground(new java.awt.Color(51, 51, 51));
        lbTextoP1.setForeground(new java.awt.Color(0, 255, 255));
        lbTextoP1.setText("Pacote 01 -  100 transformadores.................................................................................");

        lbTextoP2.setForeground(new java.awt.Color(0, 102, 255));
        lbTextoP2.setText("Pacote 02 - 500 trasnformadores..................................................................................");

        lbTextoP3.setForeground(new java.awt.Color(0, 0, 204));
        lbTextoP3.setText("Pacote 03 - 1000 transformadores...............................................................................");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTexto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbTextoP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbTextoP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbTextoP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bntPacote1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bntPacote2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bntPacote3, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(116, 116, 116))))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPacote1)
                    .addComponent(lbTextoP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPacote2)
                    .addComponent(lbTextoP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPacote3)
                    .addComponent(lbTextoP3))
                .addGap(79, 79, 79)
                .addComponent(lbTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPacote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPacote1ActionPerformed
       
         Double pacote01 = 100 * 5000.00 ;
         Double valorReal = 100 * 12000.00 ;
         Double economia01 =  valorReal - pacote01;
         Double porcentagem01 = (economia01 /valorReal) *100;
         Double economiaMes = economia01/ 12;
         Double porcentagemMes = (economiaMes/ valorReal )* 100;
        lbTexto.setText(String.format("\f total R$:%.2f assim ira economizar R$:%.2f / %.2f%% em um ano %.2f / %.2f%% por mes. \f", pacote01, economia01, porcentagem01, economiaMes, porcentagemMes));
        lbTextoP1.setForeground(Color.red);
        lbTextoP2.setForeground(Color.blue);
        lbTextoP3.setForeground(Color.blue);
      
    }//GEN-LAST:event_bntPacote1ActionPerformed

    private void bntPacote2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPacote2ActionPerformed
        Double pacote02 = 500 * 5000.00 ;
         Double valorReal = 500 * 12000.00 ;  
         Double economia02 =  valorReal - pacote02;
         Double porcentagem02 = (economia02 /valorReal) *100;
         Double economiaMes2 = economia02/ 12;
         Double porcentagemMes2 = (economiaMes2/ valorReal )* 100;
        lbTexto.setText(String.format("\f total R$:%.2f assim ira economizar R$:%.2f / %.2f%% em um ano %.2f / %.2f%% por mes. \f", pacote02, economia02, porcentagem02,economiaMes2, porcentagemMes2));
        lbTextoP2.setForeground(Color.red);
        lbTextoP1.setForeground(Color.blue);
        lbTextoP3.setForeground(Color.blue);
       
    }//GEN-LAST:event_bntPacote2ActionPerformed

    private void bntPacote3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPacote3ActionPerformed
        Double pacote03 = 500 * 5000.00 ;
         Double valorReal = 500 * 12000.00 ;  
         Double economia03 =  valorReal - pacote03;
         Double porcentagem03 = (economia03 /valorReal) *100;
         Double economiaMes3 = economia03/ 12;
         Double porcentagemMes3 = (economiaMes3/ valorReal )* 100;
        lbTexto.setText(String.format("\f total R$:%.2f assim ira economizar R$:%.2f / %.2f%% em um ano %.2f / %.2f%% por mes. \f", pacote03, economia03, porcentagem03,economiaMes3, porcentagemMes3));
        lbTextoP3.setForeground(Color.red);
        lbTextoP2.setForeground(Color.blue);
        lbTextoP1.setForeground(Color.blue);
    }//GEN-LAST:event_bntPacote3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPacote1;
    private javax.swing.JButton bntPacote2;
    private javax.swing.JButton bntPacote3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lbTextoP1;
    private javax.swing.JLabel lbTextoP2;
    private javax.swing.JLabel lbTextoP3;
    // End of variables declaration//GEN-END:variables
}
